name: PR Template Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.10.0'

    - name: Check PR template
      id: check_pr_template
      run: |
        # Fetch PR body
        PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
        
        # Define required fields
        REQUIRED_FIELDS=("Name" "Blender Version" "Script Description" "Type" "Job Type" "Envs" "Code" "Note" "Project Structure" "Entrypoint" "References" "Screenshots" "Tags")
        
        # Check each field
        MISSING_FIELDS=()
        for FIELD in "${REQUIRED_FIELDS[@]}"; do
          if ! echo "$PR_BODY" | grep -q "## $FIELD"; then
            MISSING_FIELDS+=("$FIELD")
          fi
        done
        
        # Set output and environment variable
        echo "MISSING_FIELDS=${MISSING_FIELDS[*]}" >> $GITHUB_ENV
        echo "MISSING_FIELDS_COUNT=${#MISSING_FIELDS[@]}" >> $GITHUB_ENV

    - name: Comment on PR if fields are missing
      if: ${{ env.MISSING_FIELDS_COUNT != 0 }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prNumber = context.payload.pull_request.number;
          const missingFields = process.env.MISSING_FIELDS;
          const body = `Your PR is missing some required fields. Please fill out all fields as per the template. Missing fields: ${missingFields}`;
          await github.rest.issues.createComment({
            issue_number: prNumber,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });
